# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metana < Formula
  desc "An abstract migration tool written in Go for Go services."
  homepage "https://github.com/g14a/metana"
  version "3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/g14a/metana/releases/download/v3.0/metana_3.0_darwin_amd64.tar.gz"
      sha256 "053ff3caf7711764d611302dd95edce520a7e87b19bc917545e2ac1d117a59b9"

      def install
        bin.install "metana"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/g14a/metana/releases/download/v3.0/metana_3.0_darwin_arm64.tar.gz"
      sha256 "0cdb71a495e4c79d5a24cb5fdceac93a942ebcb10414cd9027d0818f1934d847"

      def install
        bin.install "metana"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/g14a/metana/releases/download/v3.0/metana_3.0_linux_amd64.tar.gz"
        sha256 "2636db1297050f08bfa0287cbc3885a4a922c728dd5964ff40b3fc7b9dac8180"

        def install
          bin.install "metana"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/g14a/metana/releases/download/v3.0/metana_3.0_linux_arm64.tar.gz"
        sha256 "49322ddae2801256455ed9e685d2c76023ca61866f993412e64f605cbf3fd387"

        def install
          bin.install "metana"
        end
      end
    end
  end
end
