# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metana < Formula
  desc "An abstract migration tool written in Go for Go services."
  homepage "https://github.com/g14a/metana"
  version "1.7"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/g14a/metana/releases/download/v1.7/metana_1.7_darwin_amd64.tar.gz"
    sha256 "0a7c97eaa712a4b0b1716efa565624fc35aa282e4cab8a43a5c9d9348dad602c"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/g14a/metana/releases/download/v1.7/metana_1.7_darwin_arm64.tar.gz"
    sha256 "09a055b0f529cbb3bc18fa7c285b4d128b1c00d2d9def16a705f0cebada7cc6e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/g14a/metana/releases/download/v1.7/metana_1.7_linux_amd64.tar.gz"
    sha256 "32226c5faacde507673ba34184faff424fe303a4b907824caa13fa0763980b48"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/g14a/metana/releases/download/v1.7/metana_1.7_linux_arm64.tar.gz"
    sha256 "dbc9569ad24a27fc5e9cd1d53531fa055fa80f100d35b2b60b5a0572ae28c6b9"
  end

  def install
    bin.install "metana"
  end
end
